---
- name: Installer Docker via le script officiel
  hosts: serveurs
  become: true
  tasks:
    - name: Télécharger le script officiel d'installation de Docker
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Exécuter le script d'installation
      command: sh /tmp/get-docker.sh

    - name: Démarrer et activer Docker
      service:
        name: docker
        state: started
        enabled: true
